#!/bin/bash -e

USAGE="Usage: redis-conf-foot template_port count"
if [ $# -lt 2 ]; then
    echo $USAGE
    exit
fi

ip=192.168.1.145
sshport=1986
auth=shaco@1986#0621
tport=$1
count=$2

cd redis-conf

i=1
while [ $i -lt $count ]
do
    dport=$(( $tport+$i ))
    cp redis_$tport.conf redis_$dport.conf
    sed -i "s/$tport/$dport/g" redis_$dport.conf
    echo generate redis_$dport.conf
    i=$(( $i+1 ))
done

cd ..

rm -f REDIS-LIST

i=0
while [ $i -lt $count ]
do
    dport=$(( $tport+$i ))
    echo $ip $sshport $dport 0 >> REDIS-LIST
    i=$(($i+1))
done

i=0
while [ $i -lt $count ]
do
    dport=$(( $tport+$i ))
    echo -n 127.0.0.1:$dport,
    i=$(($i+1))
done
echo

i=0
while [ $i -lt $count ]
do
    dport=$(( $tport+$i ))
    echo array\(\'name\' \=\> \'user$i\', \'host\' \=\> \'$ip\', \'port\' \=\> $dport, \'auth\' \=\> \'$auth\', \'filter\' \=\> \'*\'\),
    i=$(($i+1))
done
echo

i=0
while [ $i -lt $count ]
do
    dport=$(( $tport+$i ))
    echo { \"$ip\", $dport },
    i=$(($i+1))
done
echo

rm -f redisadmin.xml
echo \<?xml version=\"1.0\"?\> >> redisadmin.xml
echo \<connections\> >> redisadmin.xml
echo \<connection name=\"acc\" host=\"$ip\" port=\"6380\" auth=\"$auth\" executeTimeout=\"60000\" connectionTimeout=\"60000\" \/\> >> redisadmin.xml
echo \<connection name=\"useruni\" host=\"$ip\" port=\"6390\" auth=\"$auth\" executeTimeout=\"60000\" connectionTimeout=\"60000\" \/\> >> redisadmin.xml
echo \<connection name=\"rank\" host=\"$ip\" port=\"6391\" auth=\"$auth\" executeTimeout=\"60000\" connectionTimeout=\"60000\" \/\> >> redisadmin.xml
i=0
while [ $i -lt $count ]
do
    dport=$(( $tport+$i ))
    echo \<connection name=\"user$i\" host=\"$ip\" port=\"$dport\" auth=\"$auth\" executeTimeout=\"60000\" connectionTimeout=\"60000\" \/\> >> redisadmin.xml
    i=$(($i+1)) 
done
echo
echo \<\/connections\> >> redisadmin.xml

