#!/bin/bash -e

# scp redis to target server
# operate redis in target server

INFO_PREFIX=[Redis]

myecho() {
    echo -en "\033[40;32;1m"
    echo $INFO_PREFIX $1
    echo -en "\033[0m"
}

force_install() {
    cd /tmp
    myecho "install $REDIS_PACKAGE ..."
    rm -f  ${REDIS_PACKAGE}.tar.gz
    rm -rf ${REDIS_PACKAGE}
    wget http://download.redis.io/releases/${REDIS_PACKAGE}.tar.gz
    tar -xf ${REDIS_PACKAGE}.tar.gz
    cd ${REDIS_PACKAGE}
    make && make PREFIX=${REDIS_BIN_DIR_PREFIX} install 
    myecho "install ok"
}

is_installed() {
    local ver=`redis-server --version | awk -F' ' '{print $3}'`
    if [ "$ver" = "v=${REDIS_VERSION}" ]; then
        return 1
    else
        return 0
    fi
}

install() {
    is_installed
    if [ $? -eq 1 ]; then
        myecho "${REDIS_PACKAGE} already install"
    else
        force_install
    fi
}

start() {
    myecho "start ${REDIS_NAME[$IS_SENTINEL]} ..."
    if [ $IS_SENTINEL -eq 0 ]; then
        ${REDIS_BIN_DIR}/${REDIS_NAME[0]} ${REDIS_CONF_DIR}/redis_${REDIS_PORT}.conf
    else
        ${REDIS_BIN_DIR}/${REDIS_NAME[0]} ${REDIS_CONF_DIR}/redis_${REDIS_PORT}.conf --sentinel
    fi
    myecho "start ${REDIS_NAME[$IS_SENTINEL]} ok"
}

stop() {
    myecho "stop ${REDIS_NAME[$IS_SENTINEL]} ..."
    ${REDIS_BIN_DIR}/redis-cli -p ${REDIS_PORT} shutdown
    myecho "stop ${REDIS_NAME[$IS_SENTINEL]} ok"
}

USAGE="Usage: redis-foot [install] [start] [stop] 
redis_port is_sentinel redis_bin_dir_prefix redis_conf_dir_prefix redis_version"

if [ $# -lt 6 ]; then
    echo $USAGE
    exit
fi
REDIS_NAME="redis-server redis-sentinel"
REDIS_NAME=($REDIS_NAME)
CMD=$1
REDIS_PORT=$2
IS_SENTINEL=$3
REDIS_BIN_DIR_PREFIX=$4
REDIS_CONF_DIR_PREFIX=$5
#REDIS_BIN_DIR_PREFIX=/usr/local
#REDIS_CONF_DIR_PREFIX=/etc
REDIS_VERSION=$6
REDIS_BIN_DIR=${REDIS_BIN_DIR_PREFIX}/bin
REDIS_CONF_DIR=${REDIS_CONF_DIR_PREFIX}/redis
REDIS_PACKAGE=redis-${REDIS_VERSION}

case "$CMD" in
install)
    install
    ;;
start)
    start
    ;;
stop)
    stop
    ;;
*)
    echo $USAGE
    ;;
esac
