#!/bin/bash -e

# scp redis to target server
# operate redis in target server

REDIS_VERSION="2.8.6"
REDIS_PACKAGE=redis-${REDIS_VERSION}
REDIS_BIN_DIR_PREFIX=/usr/local
REDIS_CONF_DIR_PREFIX=/etc
#REDIS_PORT=6379
#SENTINEL_PORT=26379

install() {
    cd /tmp
    echo install redis ...
    rm -f  ${REDIS_PACKAGE}.tar.gz
    rm -rf ${REDIS_PACKAGE}
    wget http://download.redis.io/releases/${REDIS_PACKAGE}.tar.gz
    tar -xf ${REDIS_PACKAGE}.tar.gz
    cd ${REDIS_PACKAGE}
    make && make PREFIX=${REDIS_BIN_DIR_PREFIX} install
    echo install redis ok
}

is_installed() {
    if [ `redis-server --version | awk -F'_' '{print $2}'` == "v=${REDIS_VERSION}" ]; then
        return 1
    else
        return 0
    fi
}

install() {
    is_install
    if [ $? -eq 1 ]; then
        echo ${REDIS_PACKAGE} already install
    else
        install
    fi
}

start() {
    echo start redis ...
    ${REDIS_BIN_DIR}/redis-server ${REDIS_CONF_DIR}/redis_${REDIS_PORT}.conf
    echo start redis ok
    echo start sentinel ...
    ${REDIS_BIN_DIR}/redis-server ${REDIS_CONF_DIR}/sentinel_${SENTINEL_PORT}.conf --sentinel
    echo start sentinel ok
}

stop() {
    echo stop redis ...
    ${REDIS_BIN_DIR}/redis-cli -p ${REDIS_PORT} shutdown
    echo stop redis ok
    echo stop sentinel ...
    ${REDIS_BIN_DIR}/redis-cli -p ${SENTINEL_PORT} shutdown
    echo stop sentinel ok
}

#install() {
#expect redis-install.exp 192.168.1.140 1986 root shaco@#1986 /root ./mod
#}
#login() {
#expect login.exp 192.168.1.140 1986 root shaco@#1986
#}
#startall() {
#expect<<EOF
#set timeout 30
#spawn ssh -l lvxiaojun 192.168.1.140 -p 1986
#expect "password:" 
#send "shaco1986\r"
#set timeout 30
#expect "$ "
#send "cd shaco\r"
#expect "$ "
#send "ls\r"
#expect "$ "
#EOF
#}

USAGE="Usage: redis-foot [install] [start] [stop] 
redis_port sentinel_port redis_bin_dir_prefix redis_conf_dir_prefix"

if [ $# < 5 ]; then
    echo $USAGE
    exit
fi
CMD=$1
REDIS_PORT=$2
SENTINEL_PORT=$3
REDIS_BIN_DIR_PREFIX=$4
REDIS_CONF_DIR_PREFIX=$5
REDIS_BIN_DIR=${REDIS_BIN_DIR_PREFIX}/bin
REDIS_CONF_DIR=${REDIS_CONF_DIR_PREFIX}/redis

case "$CMD" in
install)
    install
    ;;
start)
    start
    ;;
stop)
    stop
    ;;
*)
    echo $USAGE
    ;;
esac
