#!/bin/bash -e

INFO_PREFIX=[Shaco-deploy]

# deploy to every shaco machine
SHACO_DEPLOY_MACHINE_DIR=/root
SHACO_DEPLOY_MACHINE=shaco-deploy-machine
REDIS_MACHINE_FOOT=redis-machine-foot
SERVER_MACHINE_FOOT=server-machine-foot

REDIS_BIN_DIR_PREFIX=/usr/local
REDIS_CONF_DIR_PREFIX=/etc
REDIS_BIN_DIR=$REDIS_BIN_DIR_PREFIX/bin
REDIS_CONF_DIR=$REDIS_CONF_DIR_PREFIX/redis
REDIS_VERSION=`cat REDIS-VERSION`
USER=root
PASSWORD=`cat PASSWORD`

NAME="redis-server redis-sentinel"
REDIS_NAME=($NAME)

myecho() {
    echo -en "\033[40;36;1m"
    echo $INFO_PREFIX $1
    echo -en "\033[0m"
}

prepare() {
    myecho "pack $SHACO_DEPLOY_MACHINE ..."
    mkdir -p $SHACO_DEPLOY_MACHINE
    cp $REDIS_MACHINE_FOOT $SHACO_DEPLOY_MACHINE
    cp -r redis-conf $SHACO_DEPLOY_MACHINE
    tar -cf $SHACO_DEPLOY_MACHINE.tar $SHACO_DEPLOY_MACHINE
    myecho "pack $SHACO_DEPLOY_MACHINE ok"
}

clean() {
    rm -f $SHACO_DEPLOY_MACHINE.tar
    rm -rf $SHACO_DEPLOY_MACHINE
}

distribute() {
    local ip=$1; port=$2; redis_port=$3; is_sentinel=$4

    myecho "distribute host=$ip:$port ${REDIS_NAME[$is_sentinel]}=$redis_port ..."
    # distribute redis-machine-foot && redis sentinel configure
    expect scp.exp $ip $port $USER $PASSWORD $SHACO_DEPLOY_MACHINE_DIR ./$SHACO_DEPLOY_MACHINE.tar
    expect ssh.exp $ip $port $USER $PASSWORD "cd $SHACO_DEPLOY_MACHINE_DIR && 
    tar -xf $SHACO_DEPLOY_MACHINE.tar && rm -f $SHACO_DEPLOY_MACHINE.tar &&
    mkdir -p $REDIS_CONF_DIR &&
    cp $SHACO_DEPLOY_MACHINE/redis-conf/redis.conf $REDIS_CONF_DIR &&
    cp $SHACO_DEPLOY_MACHINE/redis-conf/redis_$redis_port.conf $REDIS_CONF_DIR"
    myecho "distribute ok"
}

operate_redis() {
    local ip=$1; port=$2; redis_port=$3; is_sentinel=$4; redis_op=$5
   
    myecho "$redis_op [host=$ip:$port ${REDIS_NAME[$is_sentinel]}=$redis_port] ..."
    expect ssh.exp $ip $port $USER $PASSWORD "cd $SHACO_DEPLOY_MACHINE_DIR/$SHACO_DEPLOY_MACHINE && ./$REDIS_MACHINE_FOOT $redis_op $redis_port $is_sentinel $REDIS_BIN_DIR_PREFIX $REDIS_CONF_DIR_PREFIX $REDIS_VERSION"
    myecho "$redis_op [host=$ip:$port ${REDIS_NAME[$is_sentinel]}=$redis_port] ok"
}

command() {
    local proc=$1
    local redis_op=$2

    local content=`cat REDIS-LIST`
    local OLD_IFS=${IFS}
    IFS=$'\n'
    list=(${content})
    IFS=${OLD_IFS}
   
    i=0
    while [ $i -ne ${#list[@]} ]
    do
        local one=${list[$i]}
        local arr=(${one})
        if [ ${#arr[@]} != 4 ]; then
            echo REDIS-LIST content error!!!
            exit 1
        fi
        $proc ${arr[0]} ${arr[1]} ${arr[2]} ${arr[3]} $redis_op
        
        i=$(($i+1))
    done
}

USAGE="Usage: redis-foot [distribute] [[install] [start] [stop]"

case "$1" in
distribute)
    prepare
    command distribute
    clean
    ;;
install)
    command operate_redis install
    ;;
start)
    command operate_redis start
    ;;
stop)
    command operate_redis stop
    ;;
*)
    echo $USAGE
    ;;
esac
